# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e50ec8a6f6e4d976c7554a07386dc921fdf6a436b21432d2da0913bacbb68a12692755471419d22e7fd15cb84c4eabb8cad4f09968a277354b3c0df9cc7fafd

test:
  secret_key_base: d3d247603e7c80921317d170d850b22e3a0307fd6d348d25b6bc5bf3fbcf4ed1122e20b761b7d7bab1c17f03a7931d7689113a39a66da1332e2834118dcb127d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
